# Generated by Django 4.0.5 on 2022-06-17 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='title',
            name='type',
            field=models.CharField(choices=[('Disque', 'Disque'), ('Vêtement', 'Vetement'), ('POSTERS', 'Posters'), ('DIVERS', 'Divers')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
            preserve_default=False,
        ),
    ]
